<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-09-20T19:51:07Z" name="Default suite" finished-at="2021-09-20T19:51:20Z" duration-ms="12776">
    <groups>
    </groups>
    <test started-at="2021-09-20T19:51:07Z" name="Default test" finished-at="2021-09-20T19:51:20Z" duration-ms="12776">
      <class name="ar.com.mercadolibre.pruebaTests.TC_01">
        <test-method is-config="true" signature="startWebDriver()[pri:0, instance:ar.com.mercadolibre.pruebaTests.TC_01@28276e50]" started-at="2021-09-20T16:51:07Z" name="startWebDriver" finished-at="2021-09-20T16:51:09Z" duration-ms="2324" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startWebDriver -->
        <test-method signature="TC_01_SelectLastTV()[pri:0, instance:ar.com.mercadolibre.pruebaTests.TC_01@28276e50]" started-at="2021-09-20T16:51:09Z" name="TC_01_SelectLastTV" finished-at="2021-09-20T16:51:15Z" duration-ms="5945" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at ar.com.mercadolibre.pruebaTests.TC_01.TC_01_SelectLastTV(TC_01.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_01_SelectLastTV -->
        <test-method is-config="true" signature="close()[pri:0, instance:ar.com.mercadolibre.pruebaTests.TC_01@28276e50]" started-at="2021-09-20T16:51:15Z" name="close" finished-at="2021-09-20T16:51:20Z" duration-ms="4495" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- ar.com.mercadolibre.pruebaTests.TC_01 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
